baseURL = "http://careforyourplanet.org/"
languageCode = "en-us"
title = "Care for your Planet"
theme = "hugo-serif-theme"

[params]
  google_analytics_id = ""

  [params.logo]
    mobile = "/images/logo-mobile.svg"
    standard  = "/images/logo.svg"

  [params.homepage_meta_tags]
    meta_description = "."
    meta_og_title = "Care for your Planet"
    meta_og_type = "website"
    meta_og_url = "http://careforyourplanet.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = ""


# Main Menu


